# Site settings
title: "Walkthroughs"
description: "Comprehensive game walkthroughs and guides"
url: "https://jlakko.github.io"
baseurl: "/walkthroughs"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  walkthroughs:
    output: true
    permalink: /:collection/:name/

# Default values
defaults:
  - scope:
      path: ""
      type: "walkthroughs"
    values:
      layout: "chapter"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/